# 当创建新 tag 时时，触发发布流程
# 推送 com.vrchat.clientsim 到 UPM
name: Publish VRChat SDK to UPM

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
  repository_dispatch:
    types: [publishupm]

jobs:
  publish:
    name: Publish-VRC-SDK-UPM
    runs-on: ubuntu-latest
    steps:
      # 加载仓库
      - name: Checkout
        uses: actions/checkout@v3
      # npm 安装
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # npm 登录
      - name: Publish clientsim to UPM
        run: |
          mv Packages/com.vrchat.clientsim ../com.vrchat.clientsim
          cd ../com.vrchat.clientsim
          npm set registry https://upm-packages.dev
          echo "//upm-packages.dev/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.UPM_TOKEN }}